# Generated by Django 2.2.3 on 2019-07-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('reviews', '0001_initial'),
        ('attractions', '0002_attractions_tourist_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='comments',
            field=models.ManyToManyField(to='comments.Comment'),
        ),
        migrations.AddField(
            model_name='attractions',
            name='review',
            field=models.ManyToManyField(to='reviews.Review'),
        ),
    ]
