# Generated by Django 2.2.3 on 2019-07-04 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0004_attractions_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
        ),
    ]
